name: Enforce PR from dev and build check

on:
  pull_request:
    branches: [main]

jobs:
  check-pr-source:
    name: Ensure PR comes from 'dev' branch
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is not from 'dev' branch
        run: |
          echo "Checking PR source branch..."
          echo "Source branch: ${{ github.head_ref }}"
          if [ "${{ github.head_ref }}" != "dev" ]; then
            echo "❌ Pull requests to 'main' must come from the 'dev' branch only."
            exit 1
          else
            echo "✅ Pull request is from 'dev' branch."
          fi

  build:
    name: Build project
    runs-on: ubuntu-latest
    needs: check-pr-source
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build
